// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0orWdgm0k_z4MbzF6NrbUhKajuo9BnhQ',
    appId: '1:600881030937:web:817abd69f64cf1897d0788',
    messagingSenderId: '600881030937',
    projectId: 'dulth-bf42e',
    authDomain: 'dulth-bf42e.firebaseapp.com',
    storageBucket: 'dulth-bf42e.firebasestorage.app',
    measurementId: 'G-MRH9C55846',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7cN1J_p3bQ61Ju84GlLH9IPN_I65ftc',
    appId: '1:600881030937:android:3c0dac8a3449436b7d0788',
    messagingSenderId: '600881030937',
    projectId: 'dulth-bf42e',
    storageBucket: 'dulth-bf42e.firebasestorage.app',
  );
}
